sys_name: MyLED
log_level: INFO

Strip:
  driver: Dummy
  num_leds: 488
  max_clock_speed_hz: 4000000  # [Hz] 4 MHz is the maximum for "large" strips of more than 500 LEDs.
  initial_brightness: 50  # integer from 0 to 100
  max_brightness: 75  # maximum brightness
  gamma: 2.8  # for gamma correction, put 1 to turn it off
